name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 9 * * *
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            crlf: fix
          - os: ubuntu-latest
            coverage: -Dtest-coverage=true
    runs-on: ${{matrix.os}}
    steps:
      - name: Force Line Endings for Windows
        if: ${{ matrix.crlf }}
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Run Tests
        run: |
          zig version
          zig build test -Dcomptime-tests=false ${{ matrix.coverage }}
